name: Update Packages

on:
  repository_dispatch:
  workflow_dispatch:
#   schedule:
#     - cron: '00 22 * * 5'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    name: Update packages
    strategy:
      fail-fast: false
      matrix:
        target: [main]
        
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "github-actions@ssss.fun"
        git config --global user.name "github-actions[bot]"
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x packages.sh
        git clone https://github.com/womade/OpenWrt-Packages.git packages
        cd packages
        rm -Rf *
        git rm --cache *
        $GITHUB_WORKSPACE/packages.sh
        rm -rf ./*/.git
        rm -f ./*/.gitattributes
        rm -rf ./*/.svn
        rm -rf ./*/.github
        rm -rf ./*/.gitignore
        exit 0
    - name: Upload packages
      env: 
        GITHUB_TOKEN: ${{ secrets.R_TOKEN }}
      run: |
        [ -e $GITHUB_WORKSPACE/packages.sh ] && cp $GITHUB_WORKSPACE/packages.sh $GITHUB_WORKSPACE/packages
        [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/packages
        cd $GITHUB_WORKSPACE/packages
        git add .
        git commit -m "Update$(TZ='Asia/Shanghai' date +@%Y%m%d)"
        git push --quiet "https://${{ secrets.R_TOKEN }}@github.com/womade/OpenWrt-Packages.git" HEAD:${{matrix.target}}
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
